name: Flutter CICD # action name
on:
  push:
    tags:
    - “v*”
jobs:
  build:
    runs-on: ubuntu-latest
env:
  KEY_JKS: ${{ secrets.KEY_JKS }}
  KEY_PATH: “key.jks”
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
  steps:
- uses: actions/checkout@v2
- uses: actions/setup-java@v2
  with:
    distribution: ‘adopt’
    java-version: ‘12.x’
    - name: Create key file
  run: echo $KEY_JKS | base64 -di > key.jks
    - uses: subosito/flutter-action@v1
  with:
  flutter-version: ‘2.10.2’ # change accordingly
    - run: flutter pub get
    - run: flutter build apk — release — split-per-abi
    - run: flutter build appbundle
    - name: Create github artifact release # disable this to save storage
  uses: ncipollo/release-action@v1
  with:
  artifacts: “build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab”
  token: ${{ secrets.GITHUB_TOKEN }} # this is automatically provided by github
  commit:
    - name: Upload app bundle artifact
  uses: actions/upload-artifact@v2
  with:
  name: appbundle
  path: build/app/outputs/bundle/release/app-release.aab